<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.mordent.nordaxe.plugin</groupId>
	<artifactId>plugin</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>
    <!-- nordaxe plugin -->
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.target>17</maven.compiler.target>
		<maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.release>17</maven.compiler.release>
	</properties>

  <modules>
      <module>swagger</module>
      <module>influxdb</module>
      <module>mail</module>
      <module>jetty</module>
      <module>tomcat</module>
      <module>llm</module>
  </modules>
</project>
