<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.mordent.nordaxe.framework</groupId>
	<artifactId>framework-arm</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>jar</packaging>
<!-- API Realization and Materialization -->
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.target>17</maven.compiler.target>
		<maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.release>17</maven.compiler.release>
	</properties>

	<dependencies>
	<!-- nordaxe -->
		<dependency>
			<groupId>com.mordent.nordaxe.framework</groupId>
			<artifactId>framework-api</artifactId>
        	<version>1.0.0-SNAPSHOT</version>
		</dependency>
	<!-- Log -->
		<dependency>
		    <groupId>org.apache.logging.log4j</groupId>
		    <artifactId>log4j-slf4j2-impl</artifactId>
		    <version>2.25.3</version>
		    <scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
		    <version>2.25.3</version>
		</dependency>
	<!-- Parser-->
		<dependency>
		    <groupId>org.json</groupId>
		    <artifactId>json</artifactId>
		    <version>20240303</version>
		</dependency>
		<dependency>
		    <groupId>org.yaml</groupId>
		    <artifactId>snakeyaml</artifactId>
		    <version>2.6</version>
		    <scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>de.siegmar</groupId>
			<artifactId>fastcsv</artifactId>
			<version>3.4.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>5.4.0</version>
		</dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>5.4.0</version>
        </dependency>
	<!-- charset -->
        <!--icu4j-->
        <dependency>
            <groupId>com.ibm.icu</groupId>
            <artifactId>icu4j</artifactId>
            <version>78.1</version>
        </dependency>
	<!-- Scheduler -->
		<dependency>
		    <groupId>org.quartz-scheduler</groupId>
		    <artifactId>quartz</artifactId>
		    <version>2.5.0</version>
		</dependency>
	<!-- DB-Pool -->
		<dependency>
		    <groupId>com.zaxxer</groupId>
		    <artifactId>HikariCP</artifactId>
		    <version>6.2.1</version>
		</dependency>
		<dependency>
		    <groupId>org.apache.tomcat</groupId>
		    <artifactId>tomcat-dbcp</artifactId>
		    <version>10.1.39</version>
		</dependency>
		<dependency>
		    <groupId>org.vibur</groupId>
		    <artifactId>vibur-dbcp</artifactId>
		    <version>26.0</version>
		</dependency>
		<dependency>
		    <groupId>com.oracle.database.jdbc</groupId>
		    <artifactId>ucp</artifactId>
		    <version>23.6.0.24.10</version>
		</dependency>
	<!-- jdbc -->
		<dependency>
		    <groupId>com.microsoft.sqlserver</groupId>
		    <artifactId>mssql-jdbc</artifactId>
		    <version>12.8.1.jre11</version>
		</dependency>
		<dependency>
		    <groupId>com.oracle.database.jdbc</groupId>
		    <artifactId>ojdbc11</artifactId>
		    <version>23.7.0.25.01</version>
		</dependency>
		<dependency>
			<groupId>com.oracle.database.security</groupId>
			<artifactId>oraclepki</artifactId>
			<version>23.7.0.25.01</version>
		</dependency>
		<dependency>
			<groupId>com.oracle.database.nls</groupId>
			<artifactId>orai18n</artifactId>
			<version>23.7.0.25.01</version>
		</dependency>
		<dependency>
		    <groupId>org.postgresql</groupId>
		    <artifactId>postgresql</artifactId>
		    <version>42.7.4</version>
		</dependency>
		<dependency>
		    <groupId>mysql</groupId>
		    <artifactId>mysql-connector-java</artifactId>
		    <version>8.0.33</version>
		</dependency>
		<dependency>
		    <groupId>org.mariadb.jdbc</groupId>
		    <artifactId>mariadb-java-client</artifactId>
		    <version>3.5.0</version>
		</dependency>		
	<!-- connector -->
		<!--soap-->
		<dependency>
		    <groupId>jakarta.xml.soap</groupId>
		    <artifactId>jakarta.xml.soap-api</artifactId>
		    <version>3.0.2</version>
		</dependency>	
		<dependency>
		    <groupId>com.sun.xml.messaging.saaj</groupId>
		    <artifactId>saaj-impl</artifactId>
		    <version>3.0.4</version>
		</dependency>
		<!--kafka-->
		<dependency>
		    <groupId>org.apache.kafka</groupId>
		    <artifactId>kafka-clients</artifactId>
		    <version>3.9.0</version>
		</dependency>
		<!--amqp-->
		<dependency>
			<groupId>com.rabbitmq</groupId>
			<artifactId>amqp-client</artifactId>
			<version>5.25.0</version>
		</dependency>
		<!--mqtt-->
		<dependency>
		    <groupId>org.eclipse.paho</groupId>
		    <artifactId>org.eclipse.paho.mqttv5.client</artifactId>
		    <version>1.2.5</version>
		</dependency>
		<!--hiway-->
		<dependency>
			<groupId>com.miracom.oneoone</groupId>
			<artifactId>transceiverx</artifactId>
			<version>7.0.5</version>
		</dependency>

	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>3.3.1</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals><goal>jar</goal></goals> 
					</execution>
				</executions>		
			</plugin>
		</plugins>
	</build>
</project>
